The build info shows following description: \ (#3144)
* The build info shows following description: \
Build Info: 5160073 "GNU C++ version " "5.4.0 20160609" "BOOST 107000" BUILT "Sep  3 2020" \
This file has default set to boostVersion=1.69 which is inconsitent with above build info which shows 1.70. Hence, updating default to latest Boost version to 1.75

* updating to Boost 1.70v

diff --git a/util/build_prep/centos/prep.sh.in b/util/build_prep/centos/prep.sh.in
--- a/util/build_prep/centos/prep.sh.in
+++ b/util/build_prep/centos/prep.sh.in
@@ -34,8 +34,8 @@ rm -f ./cmake_install.sh
 		exit 1
 	fi
 
-	if ! version_min 'boost --version' 1.68.999; then
-		echo "boost version too low (1.69.0+ required)" >&2
+	if ! version_min 'boost --version' 1.69.999; then
+		echo "boost version too low (1.70.0+ required)" >&2
 		exit 1
 	fi
 
